apiVersion: skaffold/v1beta11
kind: Config

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: rosscdh/hellopy
  local: {}
    # useDockerCLI: true
  #   # useBuildkit: false

deploy:
  kustomize:
    path: kustomize/argocd/dev